/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibprojekt;

/**
 *
 * @author johannilsson
 */
public class AdministratorInloggningsVal extends javax.swing.JFrame {
//Klassen för inloggningsval efter inloggning med administratörkonto.
    /**
     * Creates new form AdministratorInloggningsVal
     */
    public AdministratorInloggningsVal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AndraLosenordAdminKnapp = new javax.swing.JButton();
        TextKontoInstallningar = new javax.swing.JLabel();
        TaBortAlienKnapp = new javax.swing.JToggleButton();
        TaBortUtrustningsKnapp = new javax.swing.JToggleButton();
        SökInfoAgentKnapp = new javax.swing.JToggleButton();
        ÄndraInfoAlienKnapp = new javax.swing.JToggleButton();
        RegistreraAgentKnapp = new javax.swing.JToggleButton();
        RegistreraAlienKnapp = new javax.swing.JToggleButton();
        ÄndraInfoAgentKnapp = new javax.swing.JToggleButton();
        TaBortAgentKnapp = new javax.swing.JToggleButton();
        ÄndraOmrådeschefsKnapp = new javax.swing.JToggleButton();
        ÄndraKontorsChefsKnapp = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registreraUtrustningsknapp = new javax.swing.JToggleButton();
        platsöveraliensknapp = new javax.swing.JToggleButton();
        rassökknapp = new javax.swing.JToggleButton();
        sökinfoalienknapp = new javax.swing.JToggleButton();
        områdeschefsökkontor = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AndraLosenordAdminKnapp.setBackground(new java.awt.Color(204, 204, 255));
        AndraLosenordAdminKnapp.setForeground(new java.awt.Color(255, 255, 255));
        AndraLosenordAdminKnapp.setText("Ändra Lösenord");
        AndraLosenordAdminKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraLosenordAdminKnappActionPerformed(evt);
            }
        });
        getContentPane().add(AndraLosenordAdminKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 145, 35));

        TextKontoInstallningar.setBackground(new java.awt.Color(255, 255, 255));
        TextKontoInstallningar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextKontoInstallningar.setForeground(new java.awt.Color(255, 255, 255));
        TextKontoInstallningar.setText("Kontoinställningar");
        TextKontoInstallningar.setToolTipText("Klicka på knapparna under för att ändra dina kontoinställningar.");
        getContentPane().add(TextKontoInstallningar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 65, 203, -1));

        TaBortAlienKnapp.setBackground(new java.awt.Color(0, 153, 153));
        TaBortAlienKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TaBortAlienKnapp.setForeground(new java.awt.Color(204, 204, 204));
        TaBortAlienKnapp.setText("Ta bort Alien");
        TaBortAlienKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaBortAlienKnappActionPerformed(evt);
            }
        });
        getContentPane().add(TaBortAlienKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 183, 177, -1));

        TaBortUtrustningsKnapp.setBackground(new java.awt.Color(0, 153, 153));
        TaBortUtrustningsKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TaBortUtrustningsKnapp.setForeground(new java.awt.Color(204, 204, 204));
        TaBortUtrustningsKnapp.setText("Ta bort Utrustning");
        TaBortUtrustningsKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaBortUtrustningsKnappActionPerformed(evt);
            }
        });
        getContentPane().add(TaBortUtrustningsKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 211, 177, -1));

        SökInfoAgentKnapp.setBackground(new java.awt.Color(0, 153, 153));
        SökInfoAgentKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        SökInfoAgentKnapp.setForeground(new java.awt.Color(204, 204, 204));
        SökInfoAgentKnapp.setText("Sök Information om Agent");
        SökInfoAgentKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SökInfoAgentKnappActionPerformed(evt);
            }
        });
        getContentPane().add(SökInfoAgentKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 99, 200, -1));

        ÄndraInfoAlienKnapp.setBackground(new java.awt.Color(0, 153, 153));
        ÄndraInfoAlienKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ÄndraInfoAlienKnapp.setForeground(new java.awt.Color(204, 204, 204));
        ÄndraInfoAlienKnapp.setText("Ändra Information om Alien");
        ÄndraInfoAlienKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÄndraInfoAlienKnappActionPerformed(evt);
            }
        });
        getContentPane().add(ÄndraInfoAlienKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 127, 200, -1));

        RegistreraAgentKnapp.setBackground(new java.awt.Color(0, 153, 153));
        RegistreraAgentKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RegistreraAgentKnapp.setForeground(new java.awt.Color(204, 204, 204));
        RegistreraAgentKnapp.setText("Registrera en Agent");
        RegistreraAgentKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistreraAgentKnappActionPerformed(evt);
            }
        });
        getContentPane().add(RegistreraAgentKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 239, 177, -1));

        RegistreraAlienKnapp.setBackground(new java.awt.Color(0, 153, 153));
        RegistreraAlienKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RegistreraAlienKnapp.setForeground(new java.awt.Color(204, 204, 204));
        RegistreraAlienKnapp.setText("Registrera en Alien");
        RegistreraAlienKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistreraAlienKnappActionPerformed(evt);
            }
        });
        getContentPane().add(RegistreraAlienKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 267, 177, -1));

        ÄndraInfoAgentKnapp.setBackground(new java.awt.Color(0, 153, 153));
        ÄndraInfoAgentKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ÄndraInfoAgentKnapp.setForeground(new java.awt.Color(204, 204, 204));
        ÄndraInfoAgentKnapp.setText("Ändra information om Agent");
        ÄndraInfoAgentKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÄndraInfoAgentKnappActionPerformed(evt);
            }
        });
        getContentPane().add(ÄndraInfoAgentKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 323, -1, -1));

        TaBortAgentKnapp.setBackground(new java.awt.Color(0, 153, 153));
        TaBortAgentKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TaBortAgentKnapp.setForeground(new java.awt.Color(204, 204, 204));
        TaBortAgentKnapp.setText("Ta bort Agent");
        TaBortAgentKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaBortAgentKnappActionPerformed(evt);
            }
        });
        getContentPane().add(TaBortAgentKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 155, 177, -1));

        ÄndraOmrådeschefsKnapp.setBackground(new java.awt.Color(0, 153, 153));
        ÄndraOmrådeschefsKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ÄndraOmrådeschefsKnapp.setForeground(new java.awt.Color(204, 204, 204));
        ÄndraOmrådeschefsKnapp.setText("Ändra områdeschef ");
        ÄndraOmrådeschefsKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÄndraOmrådeschefsKnappActionPerformed(evt);
            }
        });
        getContentPane().add(ÄndraOmrådeschefsKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 127, 177, -1));

        ÄndraKontorsChefsKnapp.setBackground(new java.awt.Color(0, 153, 153));
        ÄndraKontorsChefsKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ÄndraKontorsChefsKnapp.setForeground(new java.awt.Color(204, 204, 204));
        ÄndraKontorsChefsKnapp.setText("Ändra kontorschef");
        ÄndraKontorsChefsKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÄndraKontorsChefsKnappActionPerformed(evt);
            }
        });
        getContentPane().add(ÄndraKontorsChefsKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 99, 177, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Användarhantering");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 65, 166, 28));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Användarinformation");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 65, 166, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mibprojekt/agenticon1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 379, 101, -1));

        registreraUtrustningsknapp.setBackground(new java.awt.Color(0, 153, 153));
        registreraUtrustningsknapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        registreraUtrustningsknapp.setForeground(new java.awt.Color(204, 204, 204));
        registreraUtrustningsknapp.setText("Registrera Utrustning");
        registreraUtrustningsknapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registreraUtrustningsknappActionPerformed(evt);
            }
        });
        getContentPane().add(registreraUtrustningsknapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 295, 177, -1));

        platsöveraliensknapp.setBackground(new java.awt.Color(0, 153, 153));
        platsöveraliensknapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        platsöveraliensknapp.setForeground(new java.awt.Color(204, 204, 204));
        platsöveraliensknapp.setText("Plats över aliens");
        platsöveraliensknapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platsöveraliensknappActionPerformed(evt);
            }
        });
        getContentPane().add(platsöveraliensknapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 183, 193, -1));

        rassökknapp.setBackground(new java.awt.Color(0, 153, 153));
        rassökknapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rassökknapp.setForeground(new java.awt.Color(204, 204, 204));
        rassökknapp.setText("Sök registrerade aliens (ras)");
        rassökknapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rassökknappActionPerformed(evt);
            }
        });
        getContentPane().add(rassökknapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 211, 193, -1));

        sökinfoalienknapp.setBackground(new java.awt.Color(0, 153, 153));
        sökinfoalienknapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        sökinfoalienknapp.setForeground(new java.awt.Color(204, 204, 204));
        sökinfoalienknapp.setText("Sök info om alien");
        sökinfoalienknapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sökinfoalienknappActionPerformed(evt);
            }
        });
        getContentPane().add(sökinfoalienknapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 239, 193, -1));

        områdeschefsökkontor.setBackground(new java.awt.Color(0, 153, 153));
        områdeschefsökkontor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        områdeschefsökkontor.setForeground(new java.awt.Color(204, 204, 204));
        områdeschefsökkontor.setText("Sök områdeschef för kontor");
        områdeschefsökkontor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                områdeschefsökkontorActionPerformed(evt);
            }
        });
        getContentPane().add(områdeschefsökkontor, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 267, 193, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AndraLosenordAdminKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraLosenordAdminKnappActionPerformed
        new AgentOchAdminLosenordsAndringsRuta().setVisible(true);
    }//GEN-LAST:event_AndraLosenordAdminKnappActionPerformed

    private void SökInfoAgentKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SökInfoAgentKnappActionPerformed
       new SökInformationOmAgent().setVisible(true);
    }//GEN-LAST:event_SökInfoAgentKnappActionPerformed

    private void ÄndraInfoAlienKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÄndraInfoAlienKnappActionPerformed
        new ÄndraInfoOmAlien().setVisible(true);
    }//GEN-LAST:event_ÄndraInfoAlienKnappActionPerformed

    private void RegistreraAgentKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistreraAgentKnappActionPerformed
        new RegistreraAgent().setVisible(true);
    }//GEN-LAST:event_RegistreraAgentKnappActionPerformed

    private void TaBortAgentKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaBortAgentKnappActionPerformed
        new TaBortAgent().setVisible(true);
    }//GEN-LAST:event_TaBortAgentKnappActionPerformed

    private void TaBortAlienKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaBortAlienKnappActionPerformed
        new TaBortAlien().setVisible(true);
    }//GEN-LAST:event_TaBortAlienKnappActionPerformed

    private void TaBortUtrustningsKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaBortUtrustningsKnappActionPerformed
        new TaBortUtrustning().setVisible(true);
    }//GEN-LAST:event_TaBortUtrustningsKnappActionPerformed

    private void ÄndraKontorsChefsKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÄndraKontorsChefsKnappActionPerformed
    new ÄndraKontorsChef().setVisible(true);
    }//GEN-LAST:event_ÄndraKontorsChefsKnappActionPerformed

    private void ÄndraOmrådeschefsKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÄndraOmrådeschefsKnappActionPerformed
    new ÄndraOmrådesChef().setVisible(true);
    }//GEN-LAST:event_ÄndraOmrådeschefsKnappActionPerformed

    private void ÄndraInfoAgentKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÄndraInfoAgentKnappActionPerformed
        new ÄndraInfoOmAgent().setVisible(true);
    }//GEN-LAST:event_ÄndraInfoAgentKnappActionPerformed

    private void RegistreraAlienKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistreraAlienKnappActionPerformed
        new RegistreraAlien().setVisible(true);
    }//GEN-LAST:event_RegistreraAlienKnappActionPerformed

    private void registreraUtrustningsknappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registreraUtrustningsknappActionPerformed
        new RegistreraUtrustning().setVisible(true);
    }//GEN-LAST:event_registreraUtrustningsknappActionPerformed

    private void platsöveraliensknappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platsöveraliensknappActionPerformed
         new AlienPlatsSök().setVisible(true);
    }//GEN-LAST:event_platsöveraliensknappActionPerformed

    private void rassökknappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rassökknappActionPerformed
        new AlienRasSök().setVisible(true);
    }//GEN-LAST:event_rassökknappActionPerformed

    private void sökinfoalienknappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sökinfoalienknappActionPerformed
        new AlienInfoSök().setVisible(true);
    }//GEN-LAST:event_sökinfoalienknappActionPerformed

    private void områdeschefsökkontorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_områdeschefsökkontorActionPerformed
        new OmrådesChefSök().setVisible(true);
    }//GEN-LAST:event_områdeschefsökkontorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorInloggningsVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorInloggningsVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorInloggningsVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorInloggningsVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorInloggningsVal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AndraLosenordAdminKnapp;
    private javax.swing.JToggleButton RegistreraAgentKnapp;
    private javax.swing.JToggleButton RegistreraAlienKnapp;
    private javax.swing.JToggleButton SökInfoAgentKnapp;
    private javax.swing.JToggleButton TaBortAgentKnapp;
    private javax.swing.JToggleButton TaBortAlienKnapp;
    private javax.swing.JToggleButton TaBortUtrustningsKnapp;
    private javax.swing.JLabel TextKontoInstallningar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton områdeschefsökkontor;
    private javax.swing.JToggleButton platsöveraliensknapp;
    private javax.swing.JToggleButton rassökknapp;
    private javax.swing.JToggleButton registreraUtrustningsknapp;
    private javax.swing.JToggleButton sökinfoalienknapp;
    private javax.swing.JToggleButton ÄndraInfoAgentKnapp;
    private javax.swing.JToggleButton ÄndraInfoAlienKnapp;
    private javax.swing.JToggleButton ÄndraKontorsChefsKnapp;
    private javax.swing.JToggleButton ÄndraOmrådeschefsKnapp;
    // End of variables declaration//GEN-END:variables
}
