/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibprojekt;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author johannilsson
 */
public class AgentInloggningsVal extends javax.swing.JFrame {
// Klassen för inloggningsval efter inloggning av agentkonto.
    private static InfDB idb;

    /**
     * Creates new form AgentInloggningsVal
     */
    public AgentInloggningsVal() {
        initComponents();
        
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VisaRegistreringAlienKnapp = new javax.swing.JButton();
        andraLosenOrdKnapp = new javax.swing.JButton();
        ÄndraInfoAlien = new javax.swing.JButton();
        PlatsSök = new javax.swing.JButton();
        RegAlienAvRas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        alienInfoSök = new javax.swing.JButton();
        RegistreraUtrustning = new javax.swing.JButton();
        OmrådeschefSök = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VisaRegistreringAlienKnapp.setBackground(new java.awt.Color(0, 153, 153));
        VisaRegistreringAlienKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        VisaRegistreringAlienKnapp.setForeground(new java.awt.Color(204, 204, 204));
        VisaRegistreringAlienKnapp.setText("Registrera en alien");
        VisaRegistreringAlienKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisaRegistreringAlienKnappActionPerformed(evt);
            }
        });
        getContentPane().add(VisaRegistreringAlienKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 284, 35));

        andraLosenOrdKnapp.setBackground(new java.awt.Color(204, 204, 255));
        andraLosenOrdKnapp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        andraLosenOrdKnapp.setForeground(new java.awt.Color(255, 255, 255));
        andraLosenOrdKnapp.setText("Ändra Lösenord");
        andraLosenOrdKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraLosenOrdKnappActionPerformed(evt);
            }
        });
        getContentPane().add(andraLosenOrdKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 56, 201, 35));

        ÄndraInfoAlien.setBackground(new java.awt.Color(0, 153, 153));
        ÄndraInfoAlien.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ÄndraInfoAlien.setForeground(new java.awt.Color(204, 204, 204));
        ÄndraInfoAlien.setText("Ändra information om alien");
        ÄndraInfoAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÄndraInfoAlienActionPerformed(evt);
            }
        });
        getContentPane().add(ÄndraInfoAlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 284, 35));

        PlatsSök.setBackground(new java.awt.Color(0, 153, 153));
        PlatsSök.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PlatsSök.setForeground(new java.awt.Color(204, 204, 204));
        PlatsSök.setText("Plats över aliens");
        PlatsSök.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatsSökActionPerformed(evt);
            }
        });
        getContentPane().add(PlatsSök, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 35));

        RegAlienAvRas.setBackground(new java.awt.Color(0, 153, 153));
        RegAlienAvRas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RegAlienAvRas.setForeground(new java.awt.Color(204, 204, 204));
        RegAlienAvRas.setText("Sök Registrerade Aliens (Ras)");
        RegAlienAvRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegAlienAvRasActionPerformed(evt);
            }
        });
        getContentPane().add(RegAlienAvRas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 284, 35));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AlienHantering");
        jLabel2.setToolTipText("Klicka på knapparna under för att ändra dina kontoinställningar.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 201, -1));

        alienInfoSök.setBackground(new java.awt.Color(0, 153, 153));
        alienInfoSök.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        alienInfoSök.setForeground(new java.awt.Color(204, 204, 204));
        alienInfoSök.setText("Sök information om Alien");
        alienInfoSök.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienInfoSökActionPerformed(evt);
            }
        });
        getContentPane().add(alienInfoSök, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 284, 36));

        RegistreraUtrustning.setBackground(new java.awt.Color(0, 153, 153));
        RegistreraUtrustning.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RegistreraUtrustning.setForeground(new java.awt.Color(204, 204, 204));
        RegistreraUtrustning.setText("Registrera Utrustning");
        RegistreraUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistreraUtrustningActionPerformed(evt);
            }
        });
        getContentPane().add(RegistreraUtrustning, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 201, 35));

        OmrådeschefSök.setBackground(new java.awt.Color(0, 153, 153));
        OmrådeschefSök.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        OmrådeschefSök.setForeground(new java.awt.Color(204, 204, 204));
        OmrådeschefSök.setText("Sök områdeschef för kontor");
        OmrådeschefSök.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OmrådeschefSökActionPerformed(evt);
            }
        });
        getContentPane().add(OmrådeschefSök, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 201, 35));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Kolla registrerade aliens mellan två datum");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 284, 36));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mibprojekt/agenticon1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 312, 104, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kontoinställningar");
        jLabel4.setToolTipText("Klicka på knapparna under för att ändra dina kontoinställningar.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 31, 201, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kontor & Utrustningsval");
        jLabel5.setToolTipText("Klicka på knapparna under för att ändra dina kontoinställningar.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 201, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ÄndraInfoAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÄndraInfoAlienActionPerformed
        new ÄndraInfoOmAlien().setVisible(true);
    }//GEN-LAST:event_ÄndraInfoAlienActionPerformed

    private void andraLosenOrdKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraLosenOrdKnappActionPerformed
        new AgentOchAdminLosenordsAndringsRuta().setVisible(true);
    }//GEN-LAST:event_andraLosenOrdKnappActionPerformed

    private void VisaRegistreringAlienKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisaRegistreringAlienKnappActionPerformed
        new RegistreraAlien().setVisible(true);
    }//GEN-LAST:event_VisaRegistreringAlienKnappActionPerformed

    private void PlatsSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatsSökActionPerformed
        new AlienPlatsSök().setVisible(true);
    }//GEN-LAST:event_PlatsSökActionPerformed

    private void RegAlienAvRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegAlienAvRasActionPerformed
        new AlienRasSök().setVisible(true);
    }//GEN-LAST:event_RegAlienAvRasActionPerformed

    private void alienInfoSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienInfoSökActionPerformed
        new AlienInfoSök().setVisible(true);
    }//GEN-LAST:event_alienInfoSökActionPerformed

    private void OmrådeschefSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OmrådeschefSökActionPerformed
        new OmrådesChefSök().setVisible(true);
    }//GEN-LAST:event_OmrådeschefSökActionPerformed

    private void RegistreraUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistreraUtrustningActionPerformed
        new RegistreraUtrustning().setVisible(true);
    }//GEN-LAST:event_RegistreraUtrustningActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AgentKollaRegistreradeAliensTvåDatum().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentInloggningsVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentInloggningsVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentInloggningsVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentInloggningsVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentInloggningsVal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OmrådeschefSök;
    private javax.swing.JButton PlatsSök;
    private javax.swing.JButton RegAlienAvRas;
    private javax.swing.JButton RegistreraUtrustning;
    private javax.swing.JButton VisaRegistreringAlienKnapp;
    private javax.swing.JButton alienInfoSök;
    private javax.swing.JButton andraLosenOrdKnapp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton ÄndraInfoAlien;
    // End of variables declaration//GEN-END:variables
}
