/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibprojekt;

import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author johannilsson
 */
public class RegistreraAlien extends javax.swing.JFrame {

    private static InfDB idb;
  
    public RegistreraAlien() {
        initComponents();
        
         try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registreraAlienKnapp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        registreringsdatumAlien = new javax.swing.JTextField();
        LosenordAlien = new javax.swing.JTextField();
        namnAlien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ÄndraPlatsComboBox = new javax.swing.JComboBox<>();
        ÄndraAnsvarigAgentComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        OkKnappPlats = new javax.swing.JButton();
        OkKnappAnsvarigAgent = new javax.swing.JButton();
        txtPlatsAgent = new javax.swing.JTextField();
        txtAnsvarigAgent = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        genereraIDAlien = new javax.swing.JButton();
        telefonAlien = new javax.swing.JTextField();
        alienIDlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registreraAlienKnapp.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        registreraAlienKnapp.setText("Registrera");
        registreraAlienKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registreraAlienKnappActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Registrera en Alien");

        registreringsdatumAlien.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        registreringsdatumAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registreringsdatumAlienActionPerformed(evt);
            }
        });

        LosenordAlien.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        LosenordAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LosenordAlienActionPerformed(evt);
            }
        });

        namnAlien.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        namnAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namnAlienActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("AlienID:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Plats:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Lösenord:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Namn:");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Telefon:");

        ÄndraPlatsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Borås", "Vilhelmina", "Västerås", "Örebro", " " }));
        ÄndraPlatsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÄndraPlatsComboBoxActionPerformed(evt);
            }
        });

        ÄndraAnsvarigAgentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agent O", "Agent K", "Agent J", "Agent Z" }));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Ansvarig Agent:");

        OkKnappPlats.setText("Ok");
        OkKnappPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkKnappPlatsActionPerformed(evt);
            }
        });

        OkKnappAnsvarigAgent.setText("Ok");
        OkKnappAnsvarigAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkKnappAnsvarigAgentActionPerformed(evt);
            }
        });

        txtPlatsAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlatsAgentActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Registreringsdatum:");

        genereraIDAlien.setText("Generera ID");
        genereraIDAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genereraIDAlienActionPerformed(evt);
            }
        });

        telefonAlien.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        telefonAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonAlienActionPerformed(evt);
            }
        });

        alienIDlabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        alienIDlabel.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(64, 208, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registreraAlienKnapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAnsvarigAgent)
                    .addComponent(txtPlatsAgent)
                    .addComponent(ÄndraPlatsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LosenordAlien, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(namnAlien)
                    .addComponent(registreringsdatumAlien, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(ÄndraAnsvarigAgentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefonAlien)
                    .addComponent(alienIDlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genereraIDAlien)
                    .addComponent(OkKnappPlats)
                    .addComponent(OkKnappAnsvarigAgent))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genereraIDAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(alienIDlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registreringsdatumAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LosenordAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namnAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(ÄndraPlatsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlatsAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkKnappPlats)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ÄndraAnsvarigAgentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkKnappAnsvarigAgent))
                .addGap(18, 18, 18)
                .addComponent(registreraAlienKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registreringsdatumAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registreringsdatumAlienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registreringsdatumAlienActionPerformed

    private void LosenordAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LosenordAlienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LosenordAlienActionPerformed

    private void namnAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namnAlienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namnAlienActionPerformed

    private void OkKnappPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkKnappPlatsActionPerformed
        txtPlatsAgent.setText(ÄndraPlatsComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_OkKnappPlatsActionPerformed

    private void OkKnappAnsvarigAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkKnappAnsvarigAgentActionPerformed
        txtAnsvarigAgent.setText(ÄndraAnsvarigAgentComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_OkKnappAnsvarigAgentActionPerformed

    private void registreraAlienKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registreraAlienKnappActionPerformed
        
        boolean alltokej=false;
                  
                    if (Validering.textFaltHarVarde(namnAlien)){
                  
                      if (Validering.kollaTelefonnummerTextField(telefonAlien)){
                  
                        if (Validering.kollaDatumTextField(registreringsdatumAlien)){ 

                      }
                        }
                         }
                          
                      
                   
                    alltokej=true;
                       
                     if (alltokej==true){
        try {
        
            String valdPlats = idb.fetchSingle("SELECT Plats_ID from Plats WHERE benamning = '" + txtPlatsAgent.getText() + "'");
            
                    
            String valdAgent = idb.fetchSingle("SELECT Agent_ID from Agent WHERE Namn = '" + txtAnsvarigAgent.getText() + "'"); 
            
            String uppdatera = "INSERT INTO Alien (Alien_ID, Registreringsdatum, Losenord, Namn, "
                    + "Telefon, Plats, Ansvarig_Agent) VALUES(" 
                    + alienIDlabel.getText() + ", '"
                    + registreringsdatumAlien.getText() + "', '"
                    + LosenordAlien.getText() + "', '"
                    + namnAlien.getText() + "', '"
                    + telefonAlien.getText() + "', "
                    + valdPlats + ", "
                    + valdAgent + ")";
            
            System.out.println(uppdatera);

            idb.fetchSingle(uppdatera);
            JOptionPane.showMessageDialog(null, "Ändringen lyckades!");
         
        
        } catch (InfException e) {
            System.out.println(e);
        }
        
            
        
        
        
       }                                            
    }//GEN-LAST:event_registreraAlienKnappActionPerformed

    private void ÄndraPlatsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÄndraPlatsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ÄndraPlatsComboBoxActionPerformed

    private void txtPlatsAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatsAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatsAgentActionPerformed

    private void genereraIDAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genereraIDAlienActionPerformed
        try {
            
            String fraga1 = "SELECT Alien_ID FROM Alien";
            ArrayList svar = idb.fetchRows(fraga1);
            int visadID = (svar.size() + 1);

            alienIDlabel.setText(String.valueOf(visadID));

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Ett fel uppstod.");
        }
    }//GEN-LAST:event_genereraIDAlienActionPerformed

    private void telefonAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonAlienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonAlienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistreraAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LosenordAlien;
    private javax.swing.JButton OkKnappAnsvarigAgent;
    private javax.swing.JButton OkKnappPlats;
    private javax.swing.JLabel alienIDlabel;
    private javax.swing.JButton genereraIDAlien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namnAlien;
    private javax.swing.JButton registreraAlienKnapp;
    private javax.swing.JTextField registreringsdatumAlien;
    private javax.swing.JTextField telefonAlien;
    private javax.swing.JTextField txtAnsvarigAgent;
    private javax.swing.JTextField txtPlatsAgent;
    private javax.swing.JComboBox<String> ÄndraAnsvarigAgentComboBox;
    private javax.swing.JComboBox<String> ÄndraPlatsComboBox;
    // End of variables declaration//GEN-END:variables
}
