/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibprojekt;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author johannilsson
 */
public class SökInformationOmAgent extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form SökInformationOmAgent
     */
    public SökInformationOmAgent() {
        initComponents();
        //Fyller comboboxen med alla agenter från agent-table.
        
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
          }
    private void fyllRuta()
    {
        String fraga = "SELECT Namn from Agent";
        ArrayList<String> allaAgenter;
        
        try 
        {
            allaAgenter = idb.fetchColumn(fraga);
            for (String namn : allaAgenter)
            {
                VäljAgentSökKnapp.addItem(namn);
            }
        }
        catch (InfException e)
        {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt fel");
        }
        catch (Exception e)
        {
            System.out.println("");
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VäljAgentSökKnapp = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVisaAgentInfo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Välj agent:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 67, 132, 29));

        VäljAgentSökKnapp.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        VäljAgentSökKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VäljAgentSökKnappActionPerformed(evt);
            }
        });
        getContentPane().add(VäljAgentSökKnapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 178, -1));

        txtVisaAgentInfo.setColumns(20);
        txtVisaAgentInfo.setRows(5);
        jScrollPane1.setViewportView(txtVisaAgentInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 146, 584, 484));

        jLabel2.setText("Agent_ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 118, -1, -1));

        jLabel3.setText("Namn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 118, 50, -1));

        jLabel4.setText("Telefon");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 118, -1, -1));

        jLabel5.setText("Anställningsdatum");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 118, 116, -1));

        jLabel6.setText("Lösenord");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 68, -1));

        jLabel7.setText("Admin?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 70, -1));

        jLabel8.setText("Område");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 67, -1));

        jButton1.setText("Uppdatera ruta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VäljAgentSökKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VäljAgentSökKnappActionPerformed
        txtVisaAgentInfo.setText("");
        ArrayList<HashMap<String, String>> soktaAgenter;
        
        try
        {
            String valdAgent = VäljAgentSökKnapp.getSelectedItem().toString();
            String fraga = "SELECT * FROM Agent where Namn = '" + valdAgent + "' ORDER BY Agent_ID;";
            soktaAgenter = idb.fetchRows(fraga);
            
            for (HashMap<String, String> Agent : soktaAgenter)
            {
                txtVisaAgentInfo.append(Agent.get("Agent_ID") + "\t");
                txtVisaAgentInfo.append(" " + Agent.get("Namn") + "\t");
                txtVisaAgentInfo.append(" " + Agent.get("Telefon") + "\t");
                txtVisaAgentInfo.append(" " + Agent.get("Anstallningsdatum") + "\t");
                txtVisaAgentInfo.append(" " + Agent.get("Administrator") + "\t");
                txtVisaAgentInfo.append(" " + Agent.get("Losenord") + "\t");
                txtVisaAgentInfo.append(" " + Agent.get("Omrade") + "\n");
            }
        }
        catch(InfException e)
                    {
                    JOptionPane.showMessageDialog(null, "Databasfel");
                    System.out.println("Internt felmeddelande.");
                    }
        catch(Exception e)
        {
        System.out.println("");
        }
    }//GEN-LAST:event_VäljAgentSökKnappActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    fyllRuta();    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SökInformationOmAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SökInformationOmAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SökInformationOmAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SökInformationOmAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SökInformationOmAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> VäljAgentSökKnapp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtVisaAgentInfo;
    // End of variables declaration//GEN-END:variables
}
